import boto3
import os
from datetime import datetime, timedelta, timezone

def lambda_handler(event, context):
    """
    AWS Lambda handler to automate EBS Volume backups and clean up
    snapshots older than 30 days.
    """
    # 1. Initialize the Boto3 EC2 client
    ec2_client = boto3.client('ec2')
    
    # Target configuration (Replace with your actual volume ID or use Lambda Environment Variables)
    VOLUME_ID = os.environ.get('TARGET_VOLUME_ID', 'vol-00295877ee6395d1d') 
    RETENTION_DAYS = 30
    
    print(f"🚀 Starting Automated EBS Lifecycle Management at {datetime.now(timezone.utc)}...")
    print(f"Target Volume: {VOLUME_ID}")
    
    # Define calculation metrics for the retention cutoff
    time_limit = datetime.now(timezone.utc) - timedelta(days=RETENTION_DAYS)
    print(f"Retention Window: Keeping snapshots created after {time_limit}\n")

    created_snapshots = []
    deleted_snapshots = []

    # ==========================================
    # TASK 1: Create a Snapshot of the Volume
    # ==========================================
    try:
        print(f"🔧 Initiating snapshot creation for volume {VOLUME_ID}...")
        snapshot_response = ec2_client.create_snapshot(
            VolumeId=VOLUME_ID,
            Description=f"Automated backup generated by Lambda Lifecycle Management. Source: {VOLUME_ID}",
            TagSpecifications=[
                {
                    'ResourceType': 'snapshot',
                    'Tags': [
                        {'Key': 'CreatedBy', 'Value': 'AutomatedLambdaBackup'},
                        {'Key': 'SourceVolume', 'Value': VOLUME_ID}
                    ]
                }
            ]
        )
        new_snapshot_id = snapshot_response['SnapshotId']
        created_snapshots.append(new_snapshot_id)
        print(f"✅ [SUCCESS] Created Snapshot: {new_snapshot_id} for volume {VOLUME_ID}")
        
    except Exception as e:
        print(f"❌ [ERROR] Snapshot creation failed for volume {VOLUME_ID}: {str(e)}")

    # ==========================================
    # TASK 2: List and Purge Expired Snapshots
    # ==========================================
    try:
        print(f"\n🔍 Scanning account for automated snapshots older than {RETENTION_DAYS} days...")
        
        # Filter for snapshots created by this automated system to avoid deleting human backups
        snapshots_paginator = ec2_client.get_paginator('describe_snapshots')
        page_iterator = snapshots_paginator.paginate(
            OwnerIds=['self'],
            Filters=[
                {
                    'Name': 'tag:CreatedBy',
                    'Values': ['AutomatedLambdaBackup']
                }
            ]
        )
        
        for page in page_iterator:
            for snapshot in page['Snapshots']:
                snapshot_id = snapshot['SnapshotId']
                start_time = snapshot['StartTime'] # Already timezone-aware (UTC)
                
                # Check compliance timeline
                if start_time < time_limit:
                    print(f"⚠️  [EXPIRED] Snapshot '{snapshot_id}' created at {start_time} violates retention parameters.")
                    try:
                        ec2_client.delete_snapshot(SnapshotId=snapshot_id)
                        deleted_snapshots.append(snapshot_id)
                        print(f"🗑️  [DELETED] Successfully removed expired snapshot: {snapshot_id}")
                    except Exception as delete_err:
                        print(f"❌ [ERROR] Could not delete snapshot {snapshot_id}: {str(delete_err)}")
                else:
                    print(f"🛡️  [COMPLIANT] Snapshot '{snapshot_id}' (Created: {start_time}) is within valid retention lifecycle.")
                    
    except Exception as e:
        print(f"❌ [ERROR] Snapshot compliance audit failed: {str(e)}")

    # ==========================================
    # FINAL METRIC LOGGING SUMMARY
    # ==========================================
    print("\n================= AUDIT LOG SUMMARY =================")
    print(f"• Total Snapshots Created : {len(created_snapshots)} {created_snapshots}")
    print(f"• Total Snapshots Purged  : {len(deleted_snapshots)} {deleted_snapshots}")
    print("=====================================================")

    return {
        'statusCode': 200,
        'body': {
            'message': 'EBS Lifecycle Automation successfully processed.',
            'created': created_snapshots,
            'deleted': deleted_snapshots
        }
    }